version: "3.3"
services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    networks: 
      - backend 
  server:
    build: .
    container_name: server
    depends_on:
      - db
    ports:
      - 8080:8080
    command: bash -c "npm run migrate && npm run start"
    networks: 
      - backend
    restart: always
networks: 
  backend:


