version: "3.7"
services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    restart: always
    env_file: 
      - docker-compose.env
    networks: 
      - backend 
  server:
    build: .
    container_name: server
    depends_on:
      - db
    ports:
      - 8080:8080
    command: bash -c "npm run migrate && npm run start"
    networks: 
      - backend
    restart: always
networks: 
  backend:


